version: '3'
services:
  grpc-server:
    image: frundh/demo.grpc.server
    build: 
      context: ./src/
      dockerfile: ./Grpc.Server/Dockerfile
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ASPNETCORE_ENVIRONMENT: Development
    
  grpc-client:
    image: frundh/demo.grpc.client
    build: 
      context: ./src/
      dockerfile: ./Grpc.Client/Dockerfile
    entrypoint: 
      - /bin/bash
      - -c
    command:
      - wait-for-it grpc-server:80 -s -- grpc-client send --channel=http://grpc-server:80 hello docker        
    depends_on: 
      - grpc-server
