version: '3'
services:
  grpc-server:
    image: frundh/demo.grpc.server
    build: 
      context: ./src/
      dockerfile: ./Grpc.Server/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    
  grpc-client:
    image: frundh/demo.grpc.client
    build: 
      context: ./src/
      dockerfile: ./Grpc.Client/Dockerfile
    entrypoint: 
      - /bin/bash
      - -c
    command:
      - |
        wait-for-it grpc-server:80 -s -- grpc-client send --channel=http://grpc-server:80 hello docker
        eval [ $$(curl --write-out %{http_code} --silent --output /dev/null http://grpc-server:80/api/health) = 200 ]
        eval [ $$(curl -X POST --write-out %{http_code} --silent --output /dev/null http://grpc-server:80/api/greet -H "Content-Type: application/json" -d "{\"name\":\"curl\"}") = 200 ]
    depends_on: 
      - grpc-server
